"""Fetch Google Fonts Noto Sans HK (Regular 400 + Medium 500) and rewrite paths.

Usage: `python3 tools/fetch_notohk.py`

Downloads every woff2 subset into public/fonts/notohk/ and writes
src/styles/noto-sans-hk.css with rewritten local paths. Run again any time
Google publishes a new font version (the upstream CSS ships a version token
in the URL, so existing files stay valid until you rerun this).
"""
from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSS_OUT = ROOT / "src" / "styles" / "noto-sans-hk.css"
FONTS_OUT = ROOT / "public" / "fonts" / "notohk"
UPSTREAM_CSS = (
    "https://fonts.googleapis.com/css2"
    "?family=Noto+Sans+HK:wght@400;500&display=swap"
)

# Pretend to be a modern Chrome so Google returns woff2 URLs.
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/120 Safari/537.36"
)

BLOCK_RE = re.compile(r"@font-face\s*\{[^}]*\}", re.DOTALL)
WEIGHT_RE = re.compile(r"font-weight:\s*(\d+)")
URL_RE = re.compile(r"url\(([^)]+)\)")
# Consume the url() and any trailing format(...) together so the rewrite
# doesn't leave a duplicate format hint behind.
SRC_VALUE_RE = re.compile(r"url\([^)]+\)\s*(?:format\([^)]+\))?")


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def download(url: str, dest: Path) -> None:
    if dest.exists() and dest.stat().st_size > 0:
        return
    dest.write_bytes(fetch(url))


def main() -> int:
    css = fetch(UPSTREAM_CSS).decode("utf-8")
    blocks = BLOCK_RE.findall(css)
    if not blocks:
        print("no @font-face blocks found", file=sys.stderr)
        return 1

    FONTS_OUT.mkdir(parents=True, exist_ok=True)
    CSS_OUT.parent.mkdir(parents=True, exist_ok=True)

    counters: dict[str, int] = {}
    rewritten = [
        "/* Noto Sans HK — self-hosted, generated by tools/fetch_notohk.py. */",
        "/* Do not edit by hand; regenerate to update. */",
        "",
    ]

    for block in blocks:
        weight_m = WEIGHT_RE.search(block)
        url_m = URL_RE.search(block)
        if not (weight_m and url_m):
            print(f"skipping malformed block:\n{block}", file=sys.stderr)
            continue
        weight = weight_m.group(1)
        url = url_m.group(1).strip().strip('"').strip("'")
        idx = counters.get(weight, 0)
        counters[weight] = idx + 1
        local_name = f"notohk-{weight}-{idx:03d}.woff2"
        local_path = FONTS_OUT / local_name
        print(f"[{weight}] {idx:03d} -> {local_name}", flush=True)
        try:
            download(url, local_path)
        except Exception as e:
            print(f"  FAILED {url}: {e}", file=sys.stderr)
            return 2
        new_block = SRC_VALUE_RE.sub(
            f"url('/fonts/notohk/{local_name}') format('woff2')", block
        )
        rewritten.append(new_block)
        rewritten.append("")

    CSS_OUT.write_text("\n".join(rewritten), encoding="utf-8")
    total = sum(counters.values())
    total_bytes = sum(p.stat().st_size for p in FONTS_OUT.glob("*.woff2"))
    print(
        f"\nDone. {total} subsets, {total_bytes/1024/1024:.2f} MB on disk. "
        f"Weights: {counters}"
    )
    print(f"CSS written to {CSS_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
